### PR TITLE
UniqueNameGenerator: add documentation

### PR DESCRIPTION
**Pull request by matthiasdiener**

### CODE REVIEW

**Comment by inducer** [comment]
(Ping me when CI passes.)

**Comment by kaushikcfd** [comment]
> The problem seems to be that some of the generated names seem to be hardcoded in pytato 

I would imagine there would be certain tests in pytato/loopy which depend on the earlier behavior of the UNG, those are minor and easy to fix. However, seems like there are also certain places in loopy which is leading to certain CL errors and that's alarming, let me take a look at those.

**Comment by matthiasdiener** [comment]
This does pass CI now - should we merge it @inducer @kaushikcfd ?

**Comment by inducer** [comment]
I like the doc improvements, but I'm not super sold on always generating a numerical suffix. The underlying idea to me is to generate suffixes if needed, and otherwise leave the name alone.

What was the motivation for proposing this change?

**Comment by matthiasdiener** [comment]
> What was the motivation for proposing this change?

There were a few cosmetic reasons, none of them major:

- It is (imho) surprising to see `id_0` as the *second* name generated.
- More consistency - it makes it clearer that the first name generated belongs to the same "group" as the other names. This makes it easier (imho) to pick out these names from a long log file, for example.


If you prefer, please feel free just to merge the doc changes.

**Comment by kaushikcfd** [comment]
I don't have any issues in the logic here. However, I am slightly concerned that downstream CI is broken as the recent changes in pytato/loopy do not indicate that this should have been fixed.

On trying out this branch locally:
```
(ceesd) kgk2@bock:~/projects/ceesd/pytato/test$ pip freeze | grep pytools
-e git+ssh://git@github.com/matthiasdiener/pytools.git@76a3cff2189ff0d788d409511b2e1e353b6b0a7c#egg=pytools
(ceesd) kgk2@bock:~/projects/ceesd/pytato/test$ pytest test_codegen.py::test_dict_of_named_array_codegen_avoids_recomputation 
===================================================================== test session starts =====================================================================
platform linux -- Python 3.9.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/kgk2/projects/ceesd/pytato
plugins: xdist-2.5.0, pudb-0.7.0, cov-3.0.0, forked-1.4.0
collected 1 item                                                                                                                                              

test_codegen.py F                                                                                                                                       [100%]

========================================================================== FAILURES ===========================================================================
____________________________________________________ test_dict_of_named_array_codegen_avoids_recomputation ____________________________________________________

    def test_dict_of_named_array_codegen_avoids_recomputation():
        x = pt.make_placeholder(shape=(10, 4), dtype=float, name="x")
        y = 2*x
        z = y + 4*x
    
        yz = pt.DictOfNamedArrays({"y": y, "z": z})
    
        knl = pt.generate_loopy(yz).kernel
>       assert ("y" in knl.id_to_insn["z_store"].read_dependency_names())
E       KeyError: 'z_store'

test_codegen.py:531: KeyError
=================================================================== short test summary info ===================================================================
FAILED test_codegen.py::test_dict_of_named_array_codegen_avoids_recomputation - KeyError: 'z_store'

```

**Comment by matthiasdiener** [comment]
> I don't have any issues with the logic here. However, I am slightly concerned that downstream CI is broken as the recent changes in pytato/loopy do not indicate that this should have been fixed.

🤦 

It seems that since pytato/loopy depend on pytools in their requirements.txt files, pytools (main branch?) gets reinstalled during CI preparation...

```
2022-09-15T16:12:38.2816993Z +++ pip install -r requirements.txt
2022-09-15T16:12:38.8995701Z Collecting pytools
2022-09-15T16:12:38.8999531Z   Cloning file:///home/runner/work/pytools/pytools to /tmp/pip-install-j0hn9ugq/pytools_07571ccbc49442d9a70bb679346fc2b1
2022-09-15T16:12:38.9026797Z   Running command git clone --filter=blob:none --quiet file:///home/runner/work/pytools/pytools /tmp/pip-install-j0hn9ugq/pytools_07571ccbc49442d9a70bb679346fc2b1
2022-09-15T16:12:38.9128840Z   warning: filtering not recognized by server, ignoring
2022-09-15T16:12:39.0389725Z   Note: switching to 'b0c2b15adc94711e0d7da5db1ef3318b283523b6'.
2022-09-15T16:12:39.0390099Z 
2022-09-15T16:12:39.0390472Z   You are in 'detached HEAD' state. You can look around, make experimental
2022-09-15T16:12:39.0390908Z   changes and commit them, and you can discard any commits you make in this
2022-09-15T16:12:39.0391345Z   state without impacting any branches by switching back to a branch.
2022-09-15T16:12:39.0391611Z 
2022-09-15T16:12:39.0391846Z   If you want to create a new branch to retain commits you create, you may
2022-09-15T16:12:39.0392381Z   do so (now or later) by using -c with the switch command. Example:
2022-09-15T16:12:39.0392646Z 
2022-09-15T16:12:39.0392871Z     git switch -c <new-branch-name>
2022-09-15T16:12:39.0393104Z 
2022-09-15T16:12:39.0393278Z   Or undo this operation with:
2022-09-15T16:12:39.0393492Z 
2022-09-15T16:12:39.0393642Z     git switch -
2022-09-15T16:12:39.0393846Z 
2022-09-15T16:12:39.0394095Z   Turn off this advice by setting config variable advice.detachedHead to false
2022-09-15T16:12:39.0394378Z 
2022-09-15T16:12:39.0424516Z   Resolved file:///home/runner/work/pytools/pytools to commit b0c2b15adc94711e0d7da5db1ef3318b283523b6
2022-09-15T16:12:39.0456240Z   Preparing metadata (setup.py): started
2022-09-15T16:12:39.3048500Z   Preparing metadata (setup.py): finished with status 'done'
```

**Comment by inducer** [comment]
https://github.com/inducer/ci-support/commit/14918ab0cd0190107fb0c26e8ffdcfa459465552 is an attempt to fix the (ostensibly not-functioning-as-intended) downstream CI. Thanks @kaushikcfd  for pointing that out.

**Comment by inducer** [comment]
Rerunning.

**Comment by inducer** [comment]
OK, looks like downstream CI is now correctly picking up the breakage.

**Comment by matthiasdiener** [comment]
I changed this to only the documentation changes.

**Review by kaushikcfd — APPROVED** [review]
LGTM!

**Comment by inducer** [comment]
Thx!

**Pull request merged**
