### PR TITLE
tag.py: try importing from typing first

### PR DESCRIPTION
**Pull request by matthiasdiener**
_Please squash_

### CODE REVIEW

**Comment by matthiasdiener** [comment]
Just a heads-up @inducer, Python 3.13 may need `typing-extensions` too.

**Comment by inducer** [comment]
`TypeAlias` was in 3.10? https://typing-extensions.readthedocs.io/en/latest/#typing_extensions.TypeAlias

**Comment by matthiasdiener** [comment]
> `TypeAlias` was in 3.10? https://typing-extensions.readthedocs.io/en/latest/#typing_extensions.TypeAlias

It seems to be deprecated already, and perhaps removed in 3.13? https://docs.python.org/3/library/typing.html#typing.TypeAlias

**Comment by inducer** [comment]
Yes, they introduced the `type` statement in 3.12. But that won't become usable for us until we go to a minimum version of 3.12, which will take another few years.

**Comment by inducer** [comment]
(So `TypeAlias` will be around for that same amount of time.)

**Comment by matthiasdiener** [comment]
What should we do to enable 3.13 compatibility? Require `typing_extensions` (like in this PR)?

**Comment by alexfikl** [comment]
> What should we do to enable 3.13 compatibility? Require `typing_extensions` (like in this PR)?

I'm not sure I understand the issue. `TypeAlias` is not removed in python 3.13 and the docs say that removal is not planned:
```
Removal of [TypeAlias](https://docs.python.org/3/library/typing.html#typing.TypeAlias) is not currently planned, but users are encouraged to migrate to [type](https://docs.python.org/3/reference/simple_stmts.html#type) statements.
```
What errors are you seeing?

**Comment by matthiasdiener** [comment]
The error [here](https://github.com/inducer/pytools/actions/runs/10067150871/job/27830067869):

```
________________ ERROR collecting pytools/test/test_pytools.py _________________
ImportError while importing test module '/home/runner/work/pytools/pytools/pytools/test/test_pytools.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.13.0-beta.4/x64/lib/python3.13/importlib/__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
pytools/test/test_pytools.py:32: in <module>
    from pytools.tag import tag_dataclass
pytools/tag.py:42: in <module>
    from typing_extensions import Self, dataclass_transform
E   ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by alexfikl** [comment]
> The error [here](https://github.com/inducer/pytools/actions/runs/10067150871/job/27830067869):

That looks like a little bug to me. If we're requiring `typing_extensions` conditionally in `pyproject.toml`, it should be
```python
try: 
	from typing import Self, dataclass_transform
except ImportError:
	from typing_extensions import Self, dataclass_transform
```

**Comment by inducer** [comment]
@matthiasdiener Could you make a PR with the change suggested by @alexfikl? I agree it's a bug.

**Comment by matthiasdiener** [comment]
The CI with 3.13 passed, so I just modified this PR (minus the additional CI changes), if that's ok.

**Review by alexfikl — APPROVED** [review]

**Comment by inducer** [comment]
Thx!

**Pull request merged**
